namespace DNA.CastleMinerZ.Terrain
{
	public enum BlockTypeEnum
	{
		Empty = 0,
		Dirt = 1,
		Grass = 2,
		Sand = 3,
		Lantern = 4,
		FixedLantern = 5,
		Rock = 6,
		GoldOre = 7,
		IronOre = 8,
		CopperOre = 9,
		CoalOre = 10,
		DiamondOre = 11,
		SurfaceLava = 12,
		DeepLava = 13,
		Bedrock = 14,
		Snow = 15,
		Ice = 16,
		Log = 17,
		Leaves = 18,
		Wood = 19,
		BloodStone = 20,
		SpaceRock = 21,
		IronWall = 22,
		CopperWall = 23,
		GoldenWall = 24,
		DiamondWall = 25,
		Torch = 26,
		TorchPOSX = 27,
		TorchNEGZ = 28,
		TorchNEGX = 29,
		TorchPOSZ = 30,
		TorchPOSY = 31,
		TorchNEGY = 32,
		Crate = 33,
		LowerDoorClosedZ = 34,
		LowerDoorClosedX = 35,
		LowerDoor = 36,
		UpperDoorClosed = 37,
		LowerDoorOpenZ = 38,
		LowerDoorOpenX = 39,
		UpperDoorOpen = 40,
		NumberOfBlocks = 41,
		Uninitialized = 41
	}
}
